#!/usr/bin/env bash

# will select the most recent).
CHECKPOINT_PATH="../data/model"

# Vocabulary file generated by the preprocessing script.
SKIP_THOUGHTS_VOCAB="../data/tfrecord/vocab.txt"

# Path to downloaded word2vec model.
#WORD2VEC_MODEL="${HOME}/skip_thoughts/googlenews/GoogleNews-vectors-negative300.bin"

# Output directory.
EXP_VOCAB_DIR="../data/exp_vocab"

# Build the vocabulary expansion script.
#cd tensorflow-models/skip_thoughts
#bazel build -c opt //skip_thoughts:vocabulary_expansion

# Run the vocabulary expansion script.

python vocabulary_expansion.py --skip_thoughts_model=${CHECKPOINT_PATH}  --skip_thoughts_vocab=${SKIP_THOUGHTS_VOCAB}  --output_dir=${EXP_VOCAB_DIR}
